/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewRouteImport } from './routes/new'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as VsCannyRouteImport } from './routes/vs.canny'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiFeedbackChatRouteImport } from './routes/api/feedback-chat'
import { Route as SlugRoadmapRouteImport } from './routes/$slug/roadmap'
import { Route as SlugInsightsRouteImport } from './routes/$slug/insights'
import { Route as SlugChangelogRouteImport } from './routes/$slug/changelog'
import { Route as SlugAdminRouteImport } from './routes/$slug/admin'
import { Route as ApiV1TagsRouteImport } from './routes/api/v1/tags'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as ApiV1ChangelogRouteImport } from './routes/api/v1/changelog'
import { Route as ApiV1BoardRouteImport } from './routes/api/v1/board'
import { Route as ApiCronPruneRouteImport } from './routes/api/cron/prune'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron/digest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugSettingsWebhooksRouteImport } from './routes/$slug/settings.webhooks'
import { Route as SlugSettingsShareRouteImport } from './routes/$slug/settings.share'
import { Route as SlugSettingsApiKeysRouteImport } from './routes/$slug/settings.api-keys'
import { Route as SlugSettingsAiRouteImport } from './routes/$slug/settings.ai'
import { Route as SlugPostsIdRouteImport } from './routes/$slug/posts.$id'
import { Route as ApiV1PostsIdRouteImport } from './routes/api/v1/posts.$id'
import { Route as ApiV1PostsIdVoteRouteImport } from './routes/api/v1/posts.$id.vote'
import { Route as ApiV1PostsIdCommentsRouteImport } from './routes/api/v1/posts.$id.comments'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const VsCannyRoute = VsCannyRouteImport.update({
  id: '/vs/canny',
  path: '/vs/canny',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackChatRoute = ApiFeedbackChatRouteImport.update({
  id: '/api/feedback-chat',
  path: '/api/feedback-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoadmapRoute = SlugRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugInsightsRoute = SlugInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugChangelogRoute = SlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRouteRoute,
} as any)
const ApiV1TagsRoute = ApiV1TagsRouteImport.update({
  id: '/api/v1/tags',
  path: '/api/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChangelogRoute = ApiV1ChangelogRouteImport.update({
  id: '/api/v1/changelog',
  path: '/api/v1/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BoardRoute = ApiV1BoardRouteImport.update({
  id: '/api/v1/board',
  path: '/api/v1/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPruneRoute = ApiCronPruneRouteImport.update({
  id: '/api/cron/prune',
  path: '/api/cron/prune',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSettingsWebhooksRoute = SlugSettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSettingsShareRoute = SlugSettingsShareRouteImport.update({
  id: '/settings/share',
  path: '/settings/share',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSettingsApiKeysRoute = SlugSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSettingsAiRoute = SlugSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugPostsIdRoute = SlugPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => SlugRouteRoute,
} as any)
const ApiV1PostsIdRoute = ApiV1PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1PostsIdVoteRoute = ApiV1PostsIdVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)
const ApiV1PostsIdCommentsRoute = ApiV1PostsIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/changelog': typeof SlugChangelogRoute
  '/$slug/insights': typeof SlugInsightsRoute
  '/$slug/roadmap': typeof SlugRoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/api/track': typeof ApiTrackRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/vs/canny': typeof VsCannyRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/posts/$id': typeof SlugPostsIdRoute
  '/$slug/settings/ai': typeof SlugSettingsAiRoute
  '/$slug/settings/api-keys': typeof SlugSettingsApiKeysRoute
  '/$slug/settings/share': typeof SlugSettingsShareRoute
  '/$slug/settings/webhooks': typeof SlugSettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/cron/prune': typeof ApiCronPruneRoute
  '/api/v1/board': typeof ApiV1BoardRoute
  '/api/v1/changelog': typeof ApiV1ChangelogRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/changelog': typeof SlugChangelogRoute
  '/$slug/insights': typeof SlugInsightsRoute
  '/$slug/roadmap': typeof SlugRoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/api/track': typeof ApiTrackRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/vs/canny': typeof VsCannyRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/posts/$id': typeof SlugPostsIdRoute
  '/$slug/settings/ai': typeof SlugSettingsAiRoute
  '/$slug/settings/api-keys': typeof SlugSettingsApiKeysRoute
  '/$slug/settings/share': typeof SlugSettingsShareRoute
  '/$slug/settings/webhooks': typeof SlugSettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/cron/prune': typeof ApiCronPruneRoute
  '/api/v1/board': typeof ApiV1BoardRoute
  '/api/v1/changelog': typeof ApiV1ChangelogRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/changelog': typeof SlugChangelogRoute
  '/$slug/insights': typeof SlugInsightsRoute
  '/$slug/roadmap': typeof SlugRoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/api/track': typeof ApiTrackRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/vs/canny': typeof VsCannyRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/posts/$id': typeof SlugPostsIdRoute
  '/$slug/settings/ai': typeof SlugSettingsAiRoute
  '/$slug/settings/api-keys': typeof SlugSettingsApiKeysRoute
  '/$slug/settings/share': typeof SlugSettingsShareRoute
  '/$slug/settings/webhooks': typeof SlugSettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/cron/prune': typeof ApiCronPruneRoute
  '/api/v1/board': typeof ApiV1BoardRoute
  '/api/v1/changelog': typeof ApiV1ChangelogRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/forgot-password'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/admin'
    | '/$slug/changelog'
    | '/$slug/insights'
    | '/$slug/roadmap'
    | '/api/feedback-chat'
    | '/api/track'
    | '/api/unsubscribe'
    | '/vs/canny'
    | '/$slug/'
    | '/$slug/posts/$id'
    | '/$slug/settings/ai'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/share'
    | '/$slug/settings/webhooks'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/cron/prune'
    | '/api/v1/board'
    | '/api/v1/changelog'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/forgot-password'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/admin'
    | '/$slug/changelog'
    | '/$slug/insights'
    | '/$slug/roadmap'
    | '/api/feedback-chat'
    | '/api/track'
    | '/api/unsubscribe'
    | '/vs/canny'
    | '/$slug'
    | '/$slug/posts/$id'
    | '/$slug/settings/ai'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/share'
    | '/$slug/settings/webhooks'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/cron/prune'
    | '/api/v1/board'
    | '/api/v1/changelog'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/vote'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/forgot-password'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/admin'
    | '/$slug/changelog'
    | '/$slug/insights'
    | '/$slug/roadmap'
    | '/api/feedback-chat'
    | '/api/track'
    | '/api/unsubscribe'
    | '/vs/canny'
    | '/$slug/'
    | '/$slug/posts/$id'
    | '/$slug/settings/ai'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/share'
    | '/$slug/settings/webhooks'
    | '/api/auth/$'
    | '/api/cron/digest'
    | '/api/cron/prune'
    | '/api/v1/board'
    | '/api/v1/changelog'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NewRoute: typeof NewRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiFeedbackChatRoute: typeof ApiFeedbackChatRoute
  ApiTrackRoute: typeof ApiTrackRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  VsCannyRoute: typeof VsCannyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiCronPruneRoute: typeof ApiCronPruneRoute
  ApiV1BoardRoute: typeof ApiV1BoardRoute
  ApiV1ChangelogRoute: typeof ApiV1ChangelogRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  ApiV1TagsRoute: typeof ApiV1TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/vs/canny': {
      id: '/vs/canny'
      path: '/vs/canny'
      fullPath: '/vs/canny'
      preLoaderRoute: typeof VsCannyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback-chat': {
      id: '/api/feedback-chat'
      path: '/api/feedback-chat'
      fullPath: '/api/feedback-chat'
      preLoaderRoute: typeof ApiFeedbackChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/roadmap': {
      id: '/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/$slug/roadmap'
      preLoaderRoute: typeof SlugRoadmapRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/insights': {
      id: '/$slug/insights'
      path: '/insights'
      fullPath: '/$slug/insights'
      preLoaderRoute: typeof SlugInsightsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/changelog': {
      id: '/$slug/changelog'
      path: '/changelog'
      fullPath: '/$slug/changelog'
      preLoaderRoute: typeof SlugChangelogRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/api/v1/tags': {
      id: '/api/v1/tags'
      path: '/api/v1/tags'
      fullPath: '/api/v1/tags'
      preLoaderRoute: typeof ApiV1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/changelog': {
      id: '/api/v1/changelog'
      path: '/api/v1/changelog'
      fullPath: '/api/v1/changelog'
      preLoaderRoute: typeof ApiV1ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/board': {
      id: '/api/v1/board'
      path: '/api/v1/board'
      fullPath: '/api/v1/board'
      preLoaderRoute: typeof ApiV1BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/prune': {
      id: '/api/cron/prune'
      path: '/api/cron/prune'
      fullPath: '/api/cron/prune'
      preLoaderRoute: typeof ApiCronPruneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/settings/webhooks': {
      id: '/$slug/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/$slug/settings/webhooks'
      preLoaderRoute: typeof SlugSettingsWebhooksRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/settings/share': {
      id: '/$slug/settings/share'
      path: '/settings/share'
      fullPath: '/$slug/settings/share'
      preLoaderRoute: typeof SlugSettingsShareRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/settings/api-keys': {
      id: '/$slug/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/$slug/settings/api-keys'
      preLoaderRoute: typeof SlugSettingsApiKeysRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/settings/ai': {
      id: '/$slug/settings/ai'
      path: '/settings/ai'
      fullPath: '/$slug/settings/ai'
      preLoaderRoute: typeof SlugSettingsAiRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/posts/$id': {
      id: '/$slug/posts/$id'
      path: '/posts/$id'
      fullPath: '/$slug/posts/$id'
      preLoaderRoute: typeof SlugPostsIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/api/v1/posts/$id': {
      id: '/api/v1/posts/$id'
      path: '/$id'
      fullPath: '/api/v1/posts/$id'
      preLoaderRoute: typeof ApiV1PostsIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/posts/$id/vote': {
      id: '/api/v1/posts/$id/vote'
      path: '/vote'
      fullPath: '/api/v1/posts/$id/vote'
      preLoaderRoute: typeof ApiV1PostsIdVoteRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
    '/api/v1/posts/$id/comments': {
      id: '/api/v1/posts/$id/comments'
      path: '/comments'
      fullPath: '/api/v1/posts/$id/comments'
      preLoaderRoute: typeof ApiV1PostsIdCommentsRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugAdminRoute: typeof SlugAdminRoute
  SlugChangelogRoute: typeof SlugChangelogRoute
  SlugInsightsRoute: typeof SlugInsightsRoute
  SlugRoadmapRoute: typeof SlugRoadmapRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugPostsIdRoute: typeof SlugPostsIdRoute
  SlugSettingsAiRoute: typeof SlugSettingsAiRoute
  SlugSettingsApiKeysRoute: typeof SlugSettingsApiKeysRoute
  SlugSettingsShareRoute: typeof SlugSettingsShareRoute
  SlugSettingsWebhooksRoute: typeof SlugSettingsWebhooksRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugAdminRoute: SlugAdminRoute,
  SlugChangelogRoute: SlugChangelogRoute,
  SlugInsightsRoute: SlugInsightsRoute,
  SlugRoadmapRoute: SlugRoadmapRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugPostsIdRoute: SlugPostsIdRoute,
  SlugSettingsAiRoute: SlugSettingsAiRoute,
  SlugSettingsApiKeysRoute: SlugSettingsApiKeysRoute,
  SlugSettingsShareRoute: SlugSettingsShareRoute,
  SlugSettingsWebhooksRoute: SlugSettingsWebhooksRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface ApiV1PostsIdRouteChildren {
  ApiV1PostsIdCommentsRoute: typeof ApiV1PostsIdCommentsRoute
  ApiV1PostsIdVoteRoute: typeof ApiV1PostsIdVoteRoute
}

const ApiV1PostsIdRouteChildren: ApiV1PostsIdRouteChildren = {
  ApiV1PostsIdCommentsRoute: ApiV1PostsIdCommentsRoute,
  ApiV1PostsIdVoteRoute: ApiV1PostsIdVoteRoute,
}

const ApiV1PostsIdRouteWithChildren = ApiV1PostsIdRoute._addFileChildren(
  ApiV1PostsIdRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsIdRoute: typeof ApiV1PostsIdRouteWithChildren
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsIdRoute: ApiV1PostsIdRouteWithChildren,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NewRoute: NewRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiFeedbackChatRoute: ApiFeedbackChatRoute,
  ApiTrackRoute: ApiTrackRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  VsCannyRoute: VsCannyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiCronPruneRoute: ApiCronPruneRoute,
  ApiV1BoardRoute: ApiV1BoardRoute,
  ApiV1ChangelogRoute: ApiV1ChangelogRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  ApiV1TagsRoute: ApiV1TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
