/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWebhooksRouteImport } from './routes/settings.webhooks'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as ApiFeedbackChatRouteImport } from './routes/api/feedback-chat'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1PostsIdRouteImport } from './routes/api/v1/posts.$id'
import { Route as ApiV1PostsIdVoteRouteImport } from './routes/api/v1/posts.$id.vote'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackChatRoute = ApiFeedbackChatRouteImport.update({
  id: '/api/feedback-chat',
  path: '/api/feedback-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsIdRoute = ApiV1PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1PostsIdVoteRoute = ApiV1PostsIdVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/roadmap': typeof RoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/posts/$id': typeof PostsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/roadmap': typeof RoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/posts/$id': typeof PostsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/roadmap': typeof RoadmapRoute
  '/api/feedback-chat': typeof ApiFeedbackChatRoute
  '/posts/$id': typeof PostsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/posts/$id/vote': typeof ApiV1PostsIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/board'
    | '/changelog'
    | '/demo'
    | '/docs'
    | '/insights'
    | '/roadmap'
    | '/api/feedback-chat'
    | '/posts/$id'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/webhooks'
    | '/api/auth/$'
    | '/api/v1/posts'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/board'
    | '/changelog'
    | '/demo'
    | '/docs'
    | '/insights'
    | '/roadmap'
    | '/api/feedback-chat'
    | '/posts/$id'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/webhooks'
    | '/api/auth/$'
    | '/api/v1/posts'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/vote'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/board'
    | '/changelog'
    | '/demo'
    | '/docs'
    | '/insights'
    | '/roadmap'
    | '/api/feedback-chat'
    | '/posts/$id'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/webhooks'
    | '/api/auth/$'
    | '/api/v1/posts'
    | '/api/v1/posts/$id'
    | '/api/v1/posts/$id/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRoute
  ChangelogRoute: typeof ChangelogRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  InsightsRoute: typeof InsightsRoute
  RoadmapRoute: typeof RoadmapRoute
  ApiFeedbackChatRoute: typeof ApiFeedbackChatRoute
  PostsIdRoute: typeof PostsIdRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback-chat': {
      id: '/api/feedback-chat'
      path: '/api/feedback-chat'
      fullPath: '/api/feedback-chat'
      preLoaderRoute: typeof ApiFeedbackChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/$id': {
      id: '/api/v1/posts/$id'
      path: '/$id'
      fullPath: '/api/v1/posts/$id'
      preLoaderRoute: typeof ApiV1PostsIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/posts/$id/vote': {
      id: '/api/v1/posts/$id/vote'
      path: '/vote'
      fullPath: '/api/v1/posts/$id/vote'
      preLoaderRoute: typeof ApiV1PostsIdVoteRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
  }
}

interface ApiV1PostsIdRouteChildren {
  ApiV1PostsIdVoteRoute: typeof ApiV1PostsIdVoteRoute
}

const ApiV1PostsIdRouteChildren: ApiV1PostsIdRouteChildren = {
  ApiV1PostsIdVoteRoute: ApiV1PostsIdVoteRoute,
}

const ApiV1PostsIdRouteWithChildren = ApiV1PostsIdRoute._addFileChildren(
  ApiV1PostsIdRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsIdRoute: typeof ApiV1PostsIdRouteWithChildren
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsIdRoute: ApiV1PostsIdRouteWithChildren,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRoute,
  ChangelogRoute: ChangelogRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  InsightsRoute: InsightsRoute,
  RoadmapRoute: RoadmapRoute,
  ApiFeedbackChatRoute: ApiFeedbackChatRoute,
  PostsIdRoute: PostsIdRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
